#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonaaci_recursion(num):
    a,b=1,2
    if num <= 1:
        return num
    else:
        return fibonaaci(num-1)+fibonaaci(num-2)

def fibonacci(num):
    a,b=1,2
    sum=b
    while b <= num:
        temp = a
        a,b=b,temp+b
        if b%2 == 0:
            sum += b
    return sum

print(fibonacci(1000))